// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qugyumskcgxrivmlcmza.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF1Z3l1bXNrY2d4cml2bWxjbXphIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcxNjQ0MjUsImV4cCI6MjA2Mjc0MDQyNX0.pD-cX_h5OLRE98EpEBy9r0OhqYObnpqWorRpmcXGO9E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);